### ISSUE TITLE
`sortm dt/` sorts in descending order instead of ascending

### ISSUE THREAD

**Issue by Beebeeoii** [AY2223S2-CS2103T-T11-2/tp#106]
When I executed `sortm dt/`, the meetings returned are sorted in the order of latest meeting to the earliest meeting, instead of earliest to latest.

![image](https://user-images.githubusercontent.com/55170539/227983461-69419fac-5337-40c6-b33c-5b18ab489844.png)

**Comment by chuakid** [comment]
where is breakfast with kelvin
