### ISSUE TITLE
[PE-D][Tester B] Adding two people with the same name, but different details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-2/tp#140]
Minor bug here as well!

There might be instances where you have friends with the same name but differing contact details. Hence I feel that QuickContacts should be able to add people with the same name but different contact details.

Replication:
1. add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01
2. add n/John Doe p/12345678 e/johndoeeee@example.com a/Doe street, block 321, #03-03

Expected: Both contacts added
Actual: Second contact not added

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: chongweiguan/ped#2

**Comment by KS2499** [comment]
This is not a bug, its intended since we want name to be unique.

**Comment by Beebeeoii** [comment]
@KS2499 could we add into the UG that names are case-insensitive in that case for it to be clear for users?
