### ISSUE TITLE
[PE-D][Tester E] UG example does not work for application

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-2/tp#141]
Does not work as intended based on the userguide.

It does not work for both examples shown in the ug. I've tested both and gives error.

![image.png](https://raw.githubusercontent.com/WesleyBLDC/ped/main/files/811389a5-806d-4e9a-b6a4-2d39c4786c88.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: WesleyBLDC/ped#5

**Comment by Beebeeoii** [comment]
closed by #173
