### ISSUE TITLE
[PE-D][Tester C] Typo in UG command summary for delm command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-2/tp#144]
Example states `deletem` instead of `delm`.

![4-delm-typo.png](https://raw.githubusercontent.com/hansstanley/ped/main/files/3d5da5a8-3f5f-4b71-afb5-21def150cf27.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: hansstanley/ped#4

**Comment by Beebeeoii** [comment]
closed by #173
