### ISSUE TITLE
[PE-D][Tester C] Possible typo in the help message of sortm

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-2/tp#152]
The extra `.i` may be a typo.

![6-sortm-typo.png](https://raw.githubusercontent.com/hansstanley/ped/main/files/e4f5772f-a0df-46a8-bd15-38ad8d9b1511.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: hansstanley/ped#6

**Comment by Beebeeoii** [comment]
closed by #173
