### ISSUE TITLE
[PE-D][Tester C] Persons attending events do not update with the edit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T11-2/tp#163]
Using the `edit` command to update the person's name does not update the attendees list in the corresponding events with the person.

![9-person-update.png](https://raw.githubusercontent.com/hansstanley/ped/main/files/102b9699-3f42-4498-966c-5bc011d11c7f.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: hansstanley/ped#10

**Comment by jeremykhoo-NUS** [comment]
https://github.com/AY2223S2-CS2103T-T11-2/tp/pull/191
